<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Containers\" />
    <Folder Include="DbContexts\" />
    <Folder Include="Extensions\" />
    <Folder Include="Migrations\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechnicalTasks.Domain\TechnicalTasks.Domain.csproj" />
    <ProjectReference Include="..\TechnicalTasks.Shared\TechnicalTasks.Shared.csproj" />
  </ItemGroup>

</Project>
